/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.PengaduanController;
import java.util.List;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

import model.Pengaduan;
import model.User;

/**
 *
 * @author Adyadma Renjiro
 */
public class AdminPengaduanFrame extends javax.swing.JFrame {

    private AdminHomeFrame home;
    private User user;

    /**
     * Creates new form AdminPengaduanFrame
     */
    public AdminPengaduanFrame() {
        initComponents();
    }

    public AdminPengaduanFrame(List<Pengaduan> data, User user, AdminHomeFrame home) {
        initComponents();
        setLocationRelativeTo(null);
        this.home = home;
        this.user = user;
        loadTable(data, user);
        updateStatusButton.addActionListener(evt -> updateStatus());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        buttonKembali = new javax.swing.JButton();
        diterimaRadio = new javax.swing.JRadioButton();
        diprosesRadio = new javax.swing.JRadioButton();
        selesaiRadio = new javax.swing.JRadioButton();
        dibatalkanRadio = new javax.swing.JRadioButton();
        updateStatusButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabel);

        buttonKembali.setText("Kembali");
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });

        buttonGroup1.add(diterimaRadio);
        diterimaRadio.setText("Diterima");

        buttonGroup1.add(diprosesRadio);
        diprosesRadio.setText("Diproses");

        buttonGroup1.add(selesaiRadio);
        selesaiRadio.setText("Selesai");
        selesaiRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(dibatalkanRadio);
        dibatalkanRadio.setText("Dibatalkan");

        updateStatusButton.setText("Update Status");
        updateStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStatusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diterimaRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diprosesRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selesaiRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dibatalkanRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonKembali)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(buttonKembali)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(diterimaRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(diprosesRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selesaiRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dibatalkanRadio)
                        .addGap(18, 18, 18)
                        .addComponent(updateStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        home.setVisible(true); // tampilkan homepage
        dispose();
    }//GEN-LAST:event_buttonKembaliActionPerformed

    private void selesaiRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selesaiRadioActionPerformed

    private void updateStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStatusButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateStatusButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPengaduanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPengaduanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPengaduanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPengaduanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPengaduanFrame().setVisible(true);
            }
        });
    }

    private void loadTable(List<Pengaduan> data, User user) {
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();

        model.setColumnIdentifiers(new String[]{
            "ID", "Isi", "Status", "Dari"
        });

        model.setRowCount(0);

        for (Pengaduan p : data) {
            model.addRow(new Object[]{
                p.getIdPengaduan(),
                p.getIsi(),
                p.getStatus(),
                p.getNamaUser()
            });
        }

        // sembunyikan kolom ID (cukup SEKALI)
        if (tabel.getColumnCount() > 3) {
            tabel.removeColumn(tabel.getColumnModel().getColumn(0));
        }
    }

    private void updateStatus() {

        int row = tabel.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Pilih pengaduan terlebih dahulu!",
                    "Validasi",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        String status = null;
        if (diterimaRadio.isSelected()) {
            status = "Diterima";
        } else if (diprosesRadio.isSelected()) {
            status = "Diproses";
        } else if (selesaiRadio.isSelected()) {
            status = "Selesai";
        } else if (dibatalkanRadio.isSelected()) {
            status = "Dibatalkan";
        }

        if (status == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Pilih status terlebih dahulu!",
                    "Validasi",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin mengubah status?",
                "Konfirmasi",
                JOptionPane.OK_CANCEL_OPTION
        );

        if (confirm != JOptionPane.OK_OPTION) {
            return;
        }

        int idPengaduan = (int) tabel.getModel().getValueAt(row, 0);

        PengaduanController controller = new PengaduanController();

        if (controller.updateStatusPengaduan(idPengaduan, status)) {
            JOptionPane.showMessageDialog(
                    this,
                    "Status berhasil diperbarui",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE
            );

            reloadTable();
        }
    }

    private void reloadTable() {
        PengaduanController controller = new PengaduanController();
        List<Pengaduan> data = controller.getPengaduan();
        loadTable(data, user);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JRadioButton dibatalkanRadio;
    private javax.swing.JRadioButton diprosesRadio;
    private javax.swing.JRadioButton diterimaRadio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton selesaiRadio;
    private javax.swing.JTable tabel;
    private javax.swing.JButton updateStatusButton;
    // End of variables declaration//GEN-END:variables
}
